services:
  nginx:
    build: .
    container_name: my_nginx_container  # 指定容器的名称
    ports:
      - "3456:80"  
    volumes:
      # - ./public:/usr/share/nginx/html/public  # 挂载 public 目录 
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # 使用自定义 Nginx 配置文件